services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      NODE_ENV: development
      NODE_OPTIONS: --max-old-space-size=2048
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "until nc -z db 3306; do sleep 1; done && yarn typeorm migration:run && yarn dev"
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
      MYSQL_INNODB_LOG_FILE_SIZE: 64M
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 2
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  db_data:

networks:
  default:
    driver: bridge
